Handle empty data array in completion collection
Previously, a response of { data: [] } from Backdrop would cause
this collection to crash the application.

var periods = response.data[0].values ? response.dat...
                              ^
TypeError: Cannot read property 'values' of undefined

This change ensures that the object is correctly structured before
attempting to access the length of the values array inside data.